### ISSUE TITLE
[Bug] In version 1.20.2, starting the game will crash

### ISSUE THREAD

**Issue by Format-six** [Nekiplay/MeteorPlus#100]
### In version 1.20.2, starting the game will crash

> [13:41:38] [main/INFO]: Loading Minecraft 1.20.2 with Fabric Loader 0.15.6
[13:41:38] [main/INFO]: Loading 56 mods:
	- fabric-api 0.91.6+1.20.2
	   |-- fabric-api-base 0.4.33+fce67b32a0
	   |-- fabric-api-lookup-api-v1 1.6.43+b1792f7da0
	   |-- fabric-biome-api-v1 13.0.14+b1792f7da0
	   |-- fabric-block-api-v1 1.0.12+73761d2ea0
	   |-- fabric-block-view-api-v2 1.0.1+73761d2ea0
	   |-- fabric-blockrenderlayer-v1 1.1.43+f4b7e424a0
	   |-- fabric-client-tags-api-v1 1.1.4+86b12645a0
	   |-- fabric-command-api-v1 1.2.37+f71b366fa0
	   |-- fabric-command-api-v2 2.2.16+b1792f7da0
	   |-- fabric-commands-v0 0.2.54+df3654b3a0
	   |-- fabric-containers-v0 0.1.81+df3654b3a0
	   |-- fabric-content-registries-v0 5.0.6+b1792f7da0
	   |-- fabric-convention-tags-v1 1.5.8+b1792f7da0
	   |-- fabric-crash-report-info-v1 0.2.20+f4b7e424a0
	   |-- fabric-data-generation-api-v1 13.1.11+b1792f7da0
	   |-- fabric-dimensions-v1 2.1.57+b1792f7da0
	   |-- fabric-entity-events-v1 1.5.26+b1792f7da0
	   |-- fabric-events-interaction-v0 0.6.10+b1792f7da0
	   |-- fabric-events-lifecycle-v0 0.2.70+df3654b3a0
	   |-- fabric-game-rule-api-v1 1.0.42+a44e16a6a0
	   |-- fabric-item-api-v1 2.1.33+b1792f7da0
	   |-- fabric-item-group-api-v1 4.0.15+e3d2bf3fa0
	   |-- fabric-key-binding-api-v1 1.0.38+f4b7e424a0
	   |-- fabric-keybindings-v0 0.2.36+df3654b3a0
	   |-- fabric-lifecycle-events-v1 2.2.28+c8b10480a0
	   |-- fabric-loot-api-v2 2.1.1+3ba460fba0
	   |-- fabric-message-api-v1 6.0.2+e3d2bf3fa0
	   |-- fabric-mining-level-api-v1 2.1.56+f4b7e424a0
	   |-- fabric-model-loading-api-v1 1.0.6+b1792f7da0
	   |-- fabric-models-v0 0.4.5+9386d8a7a0
	   |-- fabric-networking-api-v1 3.1.5+f4be560ba0
	   |-- fabric-object-builder-api-v1 12.1.2+2ff98d3ba0
	   |-- fabric-particles-v1 1.1.4+f4b7e424a0
	   |-- fabric-recipe-api-v1 2.0.14+52b3ebe5a0
	   |-- fabric-registry-sync-v0 4.0.12+b1792f7da0
	   |-- fabric-renderer-api-v1 3.2.1+2034447ca0
	   |-- fabric-renderer-indigo 1.5.1+2034447ca0
	   |-- fabric-renderer-registries-v1 3.2.49+df3654b3a0
	   |-- fabric-rendering-data-attachment-v1 0.3.39+73761d2ea0
	   |-- fabric-rendering-fluids-v1 3.0.30+f4b7e424a0
	   |-- fabric-rendering-v0 1.1.52+df3654b3a0
	   |-- fabric-rendering-v1 3.0.11+b1792f7da0
	   |-- fabric-resource-conditions-api-v1 2.3.11+239dafd8a0
	   |-- fabric-resource-loader-v0 0.11.12+b1792f7da0
	   |-- fabric-screen-api-v1 2.0.12+b1792f7da0
	   |-- fabric-screen-handler-api-v1 1.3.47+b1792f7da0
	   |-- fabric-sound-api-v1 1.0.14+f4b7e424a0
	   |-- fabric-transfer-api-v1 3.3.13+4944b5a5a0
	   \-- fabric-transitive-access-wideners-v1 5.0.3+fce67b32a0
	- fabricloader 0.15.6
	   \-- mixinextras 0.3.2
	- java 17
	- meteor-client 0.5.5
	- meteorplus 1.0.4
	- minecraft 1.20.2
[13:41:38] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/H:/MC/game/mC/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[13:41:38] [main/INFO]: Compatibility level set to JAVA_16
[13:41:38] [main/INFO]: Compatibility level set to JAVA_17
[13:41:39] [main/WARN]: Error loading class: baritone/command/defaults/ComeCommand (java.lang.ClassNotFoundException: baritone/command/defaults/ComeCommand)
[13:41:39] [main/WARN]: @Mixin target baritone.command.defaults.ComeCommand was not found meteor-client-baritone.mixins.json:ComeCommandMixin from mod meteor-client
[13:41:39] [main/WARN]: Error loading class: xaero/map/mods/gui/WaypointReader (java.lang.ClassNotFoundException: xaero/map/mods/gui/WaypointReader)
[13:41:39] [main/WARN]: @Mixin target xaero.map.mods.gui.WaypointReader was not found meteor-plus-xaeroworldmap.mixins.json:WaypointRendererMixin from mod meteorplus
[13:41:39] [main/WARN]: Error loading class: xaero/map/gui/GuiMap (java.lang.ClassNotFoundException: xaero/map/gui/GuiMap)
[13:41:39] [main/WARN]: @Mixin target xaero.map.gui.GuiMap was not found meteor-plus-xaeroworldmap.mixins.json:GuiMapMixin from mod meteorplus
[13:41:39] [main/WARN]: Error loading class: xaero/map/region/MapPixel (java.lang.ClassNotFoundException: xaero/map/region/MapPixel)
[13:41:39] [main/WARN]: @Mixin target xaero.map.region.MapPixel was not found meteor-plus-xaeroworldmap.mixins.json:MapPixelAccessor from mod meteorplus
[13:41:39] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.2.0).
[13:41:40] [main/WARN]: Error loading class: baritone/api/BaritoneAPI (java.lang.ClassNotFoundException: baritone/api/BaritoneAPI)
[13:41:40] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of meteordevelopment.meteorclient.systems.modules.render.Freecam failed
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:53) ~[?:?]
Caused by: java.lang.RuntimeException: Mixin transformation of meteordevelopment.meteorclient.systems.modules.render.Freecam failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_128.handler$znh000$meteor-client$onAddStackTrace(class_128.java:533) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_555(class_128.java:80) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:134) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:274) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:167) ~[1.20.2-Fabric%200.15.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	... 8 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at meteordevelopment.meteorclient.asm.Asm$Transformer.transformClassBytes(Asm.java:104) ~[meteor-client-0.5.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_128.handler$znh000$meteor-client$onAddStackTrace(class_128.java:533) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_555(class_128.java:80) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:134) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:274) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:167) ~[1.20.2-Fabric%200.15.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	... 8 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for meteor-plus.mixins.json:meteorclient.FreecamMixin from mod meteorplus during activity: [Transform -> Method onTickEvent(Lmeteordevelopment/meteorclient/events/world/TickEvent$Pre;)V -> INVOKESTATIC -> baritone/api/BaritoneAPI::getProvider:()Lbaritone/api/IBaritoneProvider;]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:313) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at meteordevelopment.meteorclient.asm.Asm$Transformer.transformClassBytes(Asm.java:104) ~[meteor-client-0.5.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_128.handler$znh000$meteor-client$onAddStackTrace(class_128.java:533) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_555(class_128.java:80) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:134) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:274) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:167) ~[1.20.2-Fabric%200.15.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	... 8 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: baritone.api.BaritoneAPI
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:786) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:772) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:738) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at meteordevelopment.meteorclient.asm.Asm$Transformer.transformClassBytes(Asm.java:104) ~[meteor-client-0.5.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_128.handler$znh000$meteor-client$onAddStackTrace(class_128.java:533) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_555(class_128.java:80) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:134) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:274) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:167) ~[1.20.2-Fabric%200.15.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	... 8 more
Caused by: java.lang.ClassNotFoundException: baritone.api.BaritoneAPI
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:786) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:772) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:738) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at meteordevelopment.meteorclient.asm.Asm$Transformer.transformClassBytes(Asm.java:104) ~[meteor-client-0.5.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_128.handler$znh000$meteor-client$onAddStackTrace(class_128.java:533) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_555(class_128.java:80) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:134) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:274) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:167) ~[1.20.2-Fabric%200.15.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	... 8 more

`

### Steps to reproduce

```bash
meteor client V0.5.5
Meteor Plus 1.0.4
fabric API V0.91.6
```

### Meteor Plus Version

1.0.4

### Minecraft Version

1.20.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.

- [X] This is a valid bug.

**Comment by Nekiplay** [comment]
[Meteor Plus 1.20.2.zip](https://github.com/Nekiplay/MeteorPlus/files/14193465/Meteor.Plus.1.20.2.zip)
