### ISSUE TITLE
Double items in the inventory  addon

### ISSUE THREAD

**Issue by nmsjayden** [Nekiplay/MeteorPlus#126]
### Describe the bug

This bug happens when you do .add item or whatever the command is twice on the same item, it will crash your client every time you open the creative inventory.

### Steps to reproduce

```bash
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 2024-05-01 07:34:43
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2487.toString()" because the return value of "net.minecraft.class_1799.method_7969()" is null
	at com.dark.zewo2.modules.Bookchat.ontick(Bookchat.java:63)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:53)
	at net.minecraft.class_310.handler$blg000$meteor-client$onPreTick(class_310.java:11329)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1289)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.dark.zewo2.modules.Bookchat.ontick(Bookchat.java:63)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:53)
	at net.minecraft.class_310.handler$blg000$meteor-client$onPreTick(class_310.java:11329)

-- Uptime --
Details:
	JVM uptime: 2088.687s
	Wall uptime: 2055.161s
	High-res time: 2051.256s
	Client ticks: 39543 ticks / 1977.150s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2564)
	at net.minecraft.class_310.method_54580(class_310.java:995)
	at net.minecraft.class_310.method_1514(class_310.java:911)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Affected level --
Details:
	All players: 4 total; [class_746['Rockstar_Mangle'/0, l='ClientLevel', x=296.25, y=55.00, z=321.46], class_745['endgamer99'/1391458, l='ClientLevel', x=288.38, y=81.00, z=335.34], class_745['null'/6504202, l='ClientLevel', x=329.38, y=68.09, z=315.50], class_745['Rockstar_Freddy'/6069474, l='ClientLevel', x=296.27, y=55.00, z=322.76]]
	Chunk stats: 65536, 100
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,65,0), Section: (at 0,1,0 in 0,4,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 162870 game time, 436522 day time
	Server brand: legacy
	Server type: Non-integrated multiplayer server
	Tracked entity count: 104

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, asteroide, automodpack, blackout, cipherstoolbox, crystal, epicalyx, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, google-chat, higtools, iris, libjf-config-core-v2, libjf-translate-v1, lyra-addon, meteor-additions, meteor-client, meteor-crash-addon, meteor-rejects, meteor-utils, meteorist, seedcrackerx-api, serverseeker, sodium, stardust, streak-addon, zewo2

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Linux (amd64) version 6.6.17-01102-gd3cec3c11146
	Java Version: 22, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 180114192 bytes (171 MiB) / 652214272 bytes (622 MiB) up to 1073741824 bytes (1024 MiB)
	CPUs: 2
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Celeron(R) N4500 @ 1.10GHz
	Identifier: Intel64 Family 6 Model 156 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 1.10
	Number of physical packages: 2
	Number of physical CPUs: 2
	Number of logical CPUs: 2
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 1374.88
	Virtual memory used (MB): 1261.57
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms512m -Xmx1024m
	Fabric Mods: 
		asteroide: Asteroide 0.1.3
		automodpack-bootstrap: AutoModpack bootstrap 1.0.0
			automodpack: AutoModpack 4.0.0-beta1
		baritone-meteor: Baritone 1.20.4-SNAPSHOT
			dev_babbaj_nether-pathfinder: nether-pathfinder 1.4.1
		blackout: Blackout 1.0.2
		cipherstoolbox: Cipher's Toolbox 0.1.0
		crystal: Crystal Reborn 1.0.1
		epicalyx: Epicalyx Addon 0.1
		fabric-api: Fabric API 0.97.0+1.20.4
			fabric-api-base: Fabric API Base 0.4.37+78d798af4f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.50+82b1bb3e4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.17+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.17+3e2216cb4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.5+78d798af4f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.47+78d798af4f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.8+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.42+f71b366f4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.21+78d798af4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.59+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.87+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.16+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.11+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.24+78d798af4f
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.5+b90db5744f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.2.5+5c0133444f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.62+78d798af4f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.2+09fc25014f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.2+389931eb4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.75+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.47+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.3.0+bcdd12964f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.27+ee30b13a4f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.42+78d798af4f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.40+df3654b34f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.1+a67ffb5d4f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.10+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.6+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.66+78d798af4f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.9+78d798af4f
			fabric-models-v0: Fabric Models (v0) 0.4.8+9386d8a74f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.8+2e5ac5484f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.1.0+dba1195c4f
			fabric-particles-v1: Fabric Particles (v1) 1.1.8+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.21+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.20+ee30b13a4f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.5+78d798af4f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.5+78d798af4f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.54+df3654b34f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.43+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.2+e761c6694f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.57+df3654b34f
			fabric-rendering-v1: Fabric Rendering (v1) 3.2.1+6fd945a04f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.15+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.21+ee30b13a4f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.18+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.56+78d798af4f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.18+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.12+90f2d7b14f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.15+78d798af4f
		fabricloader: Fabric Loader 0.15.10
			mixinextras: MixinExtras 0.3.5
		higtools: HIGTools 2.7.4
		iris: Iris 1.6.17
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: Java HotSpot(TM) 64-Bit Server VM 22
		lyra-addon: Lyra Addon 0.7.0
		meteor-additions: MeteorAdditions 1.2.0
			google-chat: GoogleChat 0.7.4
			libjf-base: LibJF Base 3.14.2
			libjf-config-core-v2: LibJF Config 3.14.2
			libjf-translate-v1: LibJF Translate 3.14.2
		meteor-client: Meteor Client 0.5.6-2054
		meteor-crash-addon: Meteor Crash Addon 0.6
		meteor-rejects: Meteor Rejects 0.3
			seedcrackerx-api: SeedCrackerX API 2.10.1
		meteor-utils: meteor-utils 1.0
		meteorist: Meteorist 1.8
		minecraft: Minecraft 1.20.4
		serverseeker: ServerSeeker 4.3.1
		sodium: Sodium 0.5.8+mc1.20.4
		stardust: Stardust 1.6.1
		streak-addon: TrouserStreak 0.9.2
		swap-crasher: Swap Crasher 1.0.1
		zewo2: Zewo2 1.0.6
	Loaded Shaderpack: (off)
	Launched Version: 1.20.4
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: virgl (Mesa Intel(R) UHD Graphics (JSL)) GL version 4.3 (Core Profile) Mesa 22.3.6, Mesa/X.org
	Window size: 1366x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 4/4 chunks
	Resource Packs: fabric
	Current Language: en_us
	Locale: en_US
	CPU: 2x Intel(R) Celeron(R) N4500 @ 1.10GHz

-- Meteor Client --

Version: 0.5.6
Dev Build: 2054

[[ Active Modules ]]

[Movement]:
anti-void
jesus
no-slow
sprint
velocity

[Render]:
boss-stack
fullbright
item-physics
nametags
tracers

[Misc]:
auto-reconnect
better-chat
extra-knockback

[Asteroide]:
auto-chatgame
chat-bot
Essentials
experimental-features

[Lyra Addon]:
no-clear-chat

[Rejects]:
anti-crash*
knockback-plus

[meteor-utils]:
advenced-tooltips

[Zewo2]:
AntiNbtBypasser
Bookchat
Chat Filter Bypass
GM-notifier
SitModule

[[ Active Hud Elements ]]
Text
{{meteor.name} #1{meteor.version}}
Text
{FPS: #1{fps}}
Text
{TPS: #1{round(server.tps, 1)}}
Text
{Ping: #1{ping}}
Text
{Speed: #1{round(player.speed, 1)}}
active-modules
Text
{Pos: #1{floor(camera.pos.x)}, {floor(camera.pos.y)}, {floor(camera.pos.z)}}
Text
{{player.opposite_dimension != "End" ? player.opposite_dimension + ":" : ""} #1{player.opposite_dimension != "End" ? "" + floor(camera.opposite_dim_pos.x) + ", " + floor(camera.opposite_dim_pos.y) + ", " + floor(camera.opposite_dim_pos.z) : ""}}
Text
{{camera.direction} #1({round(camera.yaw, 1)}, {round(camera.pitch, 1)})}
```

### Meteor Plus Version

1.0.8.8

### Minecraft Version

1.20.4

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported.

- [X] This is a valid bug.

**Comment by nmsjayden** [comment]
how to fix

**Comment by Nekiplay** [comment]
Try remove zero2
