### ISSUE TITLE
Crash on 1.19.2

### ISSUE THREAD

**Issue by Aholicknight** [Nekiplay/MeteorPlus#23]
```
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2022-12-14 03:59:55
Description: Initializing game

java.lang.NoSuchMethodError: 'meteordevelopment.meteorclient.settings.ColorSetting$Builder meteordevelopment.meteorclient.settings.ColorSetting$Builder.defaultValue(meteordevelopment.meteorclient.utils.render.color.SettingColor)'
	at olejka.meteorplus.modules.EyeFinder.<init>(EyeFinder.java:46)
	at olejka.meteorplus.MeteorPlus.onInitialize(MeteorPlus.java:56)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at meteordevelopment.meteorclient.MeteorClient.onInitializeClient(MeteorClient.java:116)
	at net.minecraft.class_310.handler$zfg004$onInit(class_310.java:7500)
	at net.minecraft.class_310.<init>(class_310.java:670)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

Is there any fix for this? Thank you!

**Comment by JacobHolman** [comment]
try 1.19.3

**Comment by I-Got-You-Dead** [comment]
If you actually read the log it has nothing to do with meteor itself, it’s caused by an addon

**Comment by JacobHolman** [comment]
they updated it to 1.19.3, i think if it doesn't work combine it with addon template 1.19.2 or 1.19.3

**Comment by I-Got-You-Dead** [comment]
Read it

**Comment by I-Got-You-Dead** [comment]
It’s a 1.19.2 addon, they are already on 1.19.3

**Comment by I-Got-You-Dead** [comment]
It only works on 1.19.2

**Comment by I-Got-You-Dead** [comment]
Simple

**Comment by Aholicknight** [comment]
Still having this issue sadly

**Comment by Nekiplay** [comment]
Meteor Plus avalible on 1.19.3
