### ISSUE TITLE
1.19.3

### ISSUE THREAD

**Issue by Lawerencium** [Nekiplay/MeteorPlus#24]
please update, if possible. something going on with Vec3 when trying to use for 1.19.3

`Stacktrace:
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504)
	at meteordevelopment.orbit.EventBus.getListeners(EventBus.java:158)
	at meteordevelopment.orbit.EventBus.lambda$getListeners$2(EventBus.java:140)
	at meteordevelopment.orbit.EventBus.getListeners(EventBus.java:152)
	at meteordevelopment.orbit.EventBus.subscribe(EventBus.java:71)
	at olejka.meteorplus.utils.algoritms.ShadyRotation.Init(ShadyRotation.java:143)
	at olejka.meteorplus.MeteorPlus.onInitialize(MeteorPlus.java:43)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at meteordevelopment.meteorclient.MeteorClient.onInitializeClient(MeteorClient.java:114)
	at net.minecraft.class_310.handler$bbo006$onInit(class_310.java:13028)
	at net.minecraft.class_310.<init>(class_310.java:675)
`

`java.lang.NoClassDefFoundError: meteordevelopment/meteorclient/utils/misc/Vec3
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504)
	at meteordevelopment.orbit.EventBus.getListeners(EventBus.java:158)
	at meteordevelopment.orbit.EventBus.lambda$getListeners$2(EventBus.java:140)
	at meteordevelopment.orbit.EventBus.getListeners(EventBus.java:152)
	at meteordevelopment.orbit.EventBus.subscribe(EventBus.java:71)
	at olejka.meteorplus.utils.algoritms.ShadyRotation.Init(ShadyRotation.java:143)
	at olejka.meteorplus.MeteorPlus.onInitialize(MeteorPlus.java:43)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at meteordevelopment.meteorclient.MeteorClient.onInitializeClient(MeteorClient.java:114)
	at net.minecraft.class_310.handler$bbo006$onInit(class_310.java:13028)
	at net.minecraft.class_310.<init>(class_310.java:675)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: meteordevelopment.meteorclient.utils.misc.Vec3
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)`

![image](https://user-images.githubusercontent.com/44242146/210284316-068a526d-73bd-4844-9f06-50827731b7c6.png)

**Comment by Nekiplay** [comment]
updated

**Comment by Lawerencium** [comment]
> updated

It seems like XRay BruteForce doesnt work? it triggers on the anti-xray diamond_ores too, so will just fill the hole ground with ESP's
