### ISSUE TITLE
[ ERROR ] 1.19.2 COMPATIBILITY 

### ISSUE THREAD

**Issue by PrimeTDMomega** [Nekiplay/MeteorPlus#26]
The version of meteorplus you've tagged with `1.19.2` is for 1.19.3, here's the file
[meteor-plus-1.1.zip](https://github.com/Nekiplay/MeteorPlus/files/10349530/meteor-plus-1.1.zip)
and here's the error - 
```
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'MeteorPlus' (meteorplus) 1.1 with any version that is compatible with:
		 - minecraft 1.19.2
Unmet dependency listing:
	 - Mod 'MeteorPlus' (meteorplus) 1.1 requires version 1.19.3 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by Nekiplay** [comment]
Meteor Plus no longer support 1.19.2

**Comment by PrimeTDMomega** [comment]
Ok
