### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Linuqsior** [Nekiplay/MeteorPlus#42]
if you enable "Better KillAura" then you crash game gives game logs:
[09:41:41] [Render thread/ERROR]: Unreported exception thrown!
java.lang.ClassCastException: class it.unimi.dsi.fastutil.objects.ObjectOpenHashSet cannot be cast to class it.unimi.dsi.fastutil.objects.Object2BooleanMap (it.unimi.dsi.fastutil.objects.ObjectOpenHashSet and it.unimi.dsi.fastutil.objects.Object2BooleanMap are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @57175e74)
	at olejka.meteorplus.modules.KillAuraBetter.entityCheck(KillAuraBetter.java:443) ~[meteor-plus-1.19.4-release-2-for-dev-build-0.5.3.jar:?]
	at meteordevelopment.meteorclient.utils.entity.TargetUtils.getList(TargetUtils.java:42) ~[meteor-client-0.5.3-1846.jar:?]
	at olejka.meteorplus.modules.KillAuraBetter.onTick(KillAuraBetter.java:365) ~[meteor-plus-1.19.4-release-2-for-dev-build-0.5.3.jar:?]
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83) ~[meteor-client-0.5.3-1846.jar:?]
	at meteordevelopment.orbit.EventBus.post(EventBus.java:47) ~[meteor-client-0.5.3-1846.jar:?]
	at net.minecraft.class_310.handler$zoi000$meteor-client$onPreTick(class_310.java:7059) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1180) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:801) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) ~[fabric-loader-0.14.21-1.19.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]

**Comment by secretisadev** [comment]
is this fixed?

**Comment by Nekiplay** [comment]
The problem is not properly configured module, KillAura Plus - KillAura Better has long been planned to be rewritten
