### ISSUE TITLE
[Bug] Crash - Clicking deselect all for enchantment list causes crash

### ISSUE THREAD

**Issue by PoTheMagicDragon** [Nekiplay/MeteorPlus#87]
### Describe the bug

See the title.

Here's the crash:
```
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Runnable.run()" because "button.action" is null
	at meteordevelopment.meteorclient.gui.screens.settings.LeftRightListSettingScreen.mdd400f1$meteorplus$lambda$initWidgets$0$3(LeftRightListSettingScreen.java:559) ~[meteor-client-0.5.4-SNAPSHOT.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at meteordevelopment.meteorclient.gui.screens.settings.LeftRightListSettingScreen.mdd400f1$meteorplus$lambda$initWidgets$1$2(LeftRightListSettingScreen.java:557) ~[meteor-client-0.5.4-SNAPSHOT.jar:?]
	at meteordevelopment.meteorclient.gui.widgets.pressable.WPressable.onMouseReleased(WPressable.java:28) ~[meteor-client-0.5.4-SNAPSHOT.jar:?]
```

<details>
<summary>Here's the crash log (at least the relevant parts):</summary>

```  
net.minecraft.util.crash.CrashException: mouseReleased event handler
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:461) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse.java:97) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.client.Mouse.method_22686(Mouse.java:171) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:101) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.client.Mouse.method_22684(Mouse.java:171) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:build 7]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:167) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:176) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.client.util.Window.swapBuffers(Window.java:275) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1142) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:774) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Runnable.run()" because "button.action" is null
	at meteordevelopment.meteorclient.gui.screens.settings.LeftRightListSettingScreen.mdd400f1$meteorplus$lambda$initWidgets$0$3(LeftRightListSettingScreen.java:559) ~[meteor-client-0.5.4-SNAPSHOT.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at meteordevelopment.meteorclient.gui.screens.settings.LeftRightListSettingScreen.mdd400f1$meteorplus$lambda$initWidgets$1$2(LeftRightListSettingScreen.java:557) ~[meteor-client-0.5.4-SNAPSHOT.jar:?]
	at meteordevelopment.meteorclient.gui.widgets.pressable.WPressable.onMouseReleased(WPressable.java:28) ~[meteor-client-0.5.4-SNAPSHOT.jar:?]
	at meteordevelopment.meteorclient.gui.widgets.WWidget.mouseReleased(WWidget.java:96) ~[meteor-client-0.5.4-SNAPSHOT.jar:?]
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:142) ~[meteor-client-0.5.4-SNAPSHOT.jar:?]
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:142) ~[meteor-client-0.5.4-SNAPSHOT.jar:?]
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:142) ~[meteor-client-0.5.4-SNAPSHOT.jar:?]
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:142) ~[meteor-client-0.5.4-SNAPSHOT.jar:?]
	at meteordevelopment.meteorclient.gui.WidgetScreen.mouseReleased(WidgetScreen.java:136) ~[meteor-client-0.5.4-SNAPSHOT.jar:?]
	at net.minecraft.client.Mouse.method_1605(Mouse.java:97) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:451) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	... 17 more
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2023-12-20 15:46:01
Description: mouseReleased event handler

java.lang.NullPointerException: Cannot invoke "java.lang.Runnable.run()" because "button.action" is null
	at meteordevelopment.meteorclient.gui.screens.settings.LeftRightListSettingScreen.mdd400f1$meteorplus$lambda$initWidgets$0$3(LeftRightListSettingScreen.java:559)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at meteordevelopment.meteorclient.gui.screens.settings.LeftRightListSettingScreen.mdd400f1$meteorplus$lambda$initWidgets$1$2(LeftRightListSettingScreen.java:557)
	at meteordevelopment.meteorclient.gui.widgets.pressable.WPressable.onMouseReleased(WPressable.java:28)
	at meteordevelopment.meteorclient.gui.widgets.WWidget.mouseReleased(WWidget.java:96)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:142)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:142)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:142)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:142)
	at meteordevelopment.meteorclient.gui.WidgetScreen.mouseReleased(WidgetScreen.java:136)
	at net.minecraft.client.Mouse.method_1605(Mouse.java:97)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:451)
	at net.minecraft.client.Mouse.onMouseButton(Mouse.java:97)
	at net.minecraft.client.Mouse.method_22686(Mouse.java:171)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:101)
	at net.minecraft.client.Mouse.method_22684(Mouse.java:171)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:167)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:176)
	at net.minecraft.client.util.Window.swapBuffers(Window.java:275)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1142)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:774)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at meteordevelopment.meteorclient.gui.screens.settings.LeftRightListSettingScreen.mdd400f1$meteorplus$lambda$initWidgets$0$3(LeftRightListSettingScreen.java:559)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at meteordevelopment.meteorclient.gui.screens.settings.LeftRightListSettingScreen.mdd400f1$meteorplus$lambda$initWidgets$1$2(LeftRightListSettingScreen.java:557)
	at meteordevelopment.meteorclient.gui.widgets.pressable.WPressable.onMouseReleased(WPressable.java:28)
	at meteordevelopment.meteorclient.gui.widgets.WWidget.mouseReleased(WWidget.java:96)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:142)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:142)
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Runnable.run()" because "button.action" is null

	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:142)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:142)
	at meteordevelopment.meteorclient.gui.WidgetScreen.mouseReleased(WidgetScreen.java:136)
	at net.minecraft.client.Mouse.method_1605(Mouse.java:97)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:451)
	at net.minecraft.client.Mouse.onMouseButton(Mouse.java:97)
	at net.minecraft.client.Mouse.method_22686(Mouse.java:171)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:101)
	at net.minecraft.client.Mouse.method_22684(Mouse.java:171)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:167)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:176)

-- Affected screen --
Details:
	Screen name: meteordevelopment.meteorclient.gui.screens.settings.EnchantmentListSettingScreen
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:451)
	at net.minecraft.client.Mouse.onMouseButton(Mouse.java:97)
	at net.minecraft.client.Mouse.method_22686(Mouse.java:171)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:101)
	at net.minecraft.client.Mouse.method_22684(Mouse.java:171)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:167)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:176)
	at net.minecraft.client.util.Window.swapBuffers(Window.java:275)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1142)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:774)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Player396'/144, l='ClientLevel', x=-1.50, y=74.00, z=10.50]]
	Chunk stats: 961, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,74,0), Section: (at 0,10,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 20692 game time, 2800 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.addDetailsToCrashReport(ClientWorld.java:428)
	at net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient.java:2132)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:790)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

```

</details>

And here's the file/ line referenced in the crash
https://github.com/Nekiplay/MeteorPlus/blob/main/src/main/java/nekiplay/meteorplus/mixin/meteorclient/LeftRightSettingsScreenMixin.java#L56-L71

Sorry if this is a repeat/ it's already been fixed. As far as I can tell, it hasn't, but I might have missed something

### Steps to reproduce

```bash
1. Open the meteor gui
2. Right click "Auto Armor"
3. Click Avoided Enchantments
4. Click Deselect All
```

### Meteor Plus Version

1.0.3

### Minecraft Version

1.20.1

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported.

- [X] This is a valid bug.

**Comment by Nekiplay** [comment]
Older versions are not supported
